version: '3.1'
services:
  pgloader:
    container_name: wmcp-pgloader
    image: dimitri/pgloader
    command:
      - /bin/sh
      - -c
      - "pgloader mysql://dbuser:MySQL123@mysql/whatsmycut postgresql://dbuser:123@postgres/whatsmycut"
  pgadmin:
    container_name: wmcp-pgadmin
    image: crunchydata/crunchy-pgadmin4:centos7-10.9-2.4.1
    volumes:
      - /var/lib/pgadmin
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_SETUP_EMAIL=dbuser@whatsmycut.com
      - PGADMIN_SETUP_PASSWORD=123
      - SERVER_PORT=5050
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: wmcp-db
    image: postgres:9.6-alpine
    user: "postgres"
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "11001:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=whatsmycut
    # restart: always
  web:
    container_name: wmcp-web
    build:
      context: ../web/
      dockerfile: ./Dockerfile
    depends_on:
      - api
    ports:
      - 3000:3000
  api:
    container_name: wmcp-api
    build:
      context: ../api/
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ..:/src
      - $SSH_AUTH_SOCK:/ssh-agent
  api2:
    depends_on:
      - postgres
    container_name: wmcp-api2
    build:
      context: ../api2/
      dockerfile: ./Dockerfile
    ports:
      - 6000:6000
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ..:/src
      - $SSH_AUTH_SOCK:/ssh-agent
  mysql:
    container_name: wmcp-mysql
    # image: mysql/mysql-server
    build:
      context: ../mysql-server/
      dockerfile: ./Dockerfile
    entrypoint: ./docker-entrypoint.sh
    command:
      - mysqld
      - --verbose
      - --default-authentication-plugin=mysql_native_password
      - --innodb-use-native-aio=0
      - --innodb-buffer-pool-size=20M
    environment:
      MYSQL_DATABASE: whatsmycut
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: MySQL123
    ports:
      - 3306:3306
  adminer:
    container_name: wmcp-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
  prisma:
    container_name: wmcp-prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    depends_on:
      - postgres
    environment:
      PRISMA_MANAGEMENT_API_SECRET: 123
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: 123
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            database: whatsmycut
            schema: whatsmycut$public
            user: dbuser
            password: 123
            migrations: false
            rawAccess: true
            ssl: false
networks:
  default:
    external:
      name: localnet

